# Generated by Django 4.1.2 on 2023-01-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=400, verbose_name='Лайки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='user_article',
            field=models.ManyToManyField(blank=True, related_name='user_article', to='webapp.like'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment',
            field=models.ManyToManyField(blank=True, related_name='user_comment', to='webapp.like'),
        ),
    ]
